### ISSUE TITLE
what's up with OFXOSC_TYPE_BUNDLE

### ISSUE THREAD

**Issue by artificiel** [2bbb/ofxSmartOscSender#2]
it's referred here:

https://github.com/2bbb/ofxSmartOscSender/blob/5be72aa47f7b83ae83cf929fd0a7affa5403abab/src/ofxOscMessageOstreamExtension.cpp#L72

but it seems to be removed from OF since 10+ years?

**Comment by 2bbb** [comment]
@artificiel 
thanks for pointing out!

I don't know why I add that line... 
but I'll fix it soon!!

**Comment by 2bbb** [comment]
@artificiel 

I fixed you point out.
thanks!

**Comment by artificiel** [comment]
super!
