### ISSUE TITLE
duplicate symbol

### ISSUE THREAD

**Issue by artificiel** [2bbb/ofxSmartOscSender#4]
on a fresh install within of-git I get an error:
```
duplicate symbol 'operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, ofxOscMessage const&)' in:
    /Users/brtn/Library/Developer/Xcode/DerivedData/668___supersonic_-_broker-evhtwwufvtcbaaeoxgjlyuohiiqv/Build/Intermediates.noindex/668 _ supersonic - broker.build/Debug/668 _ supersonic - broker.build/Objects-normal/arm64/ofxOscMessage.o
    /Users/brtn/Library/Developer/Xcode/DerivedData/668___supersonic_-_broker-evhtwwufvtcbaaeoxgjlyuohiiqv/Build/Intermediates.noindex/668 _ supersonic - broker.build/Debug/668 _ supersonic - broker.build/Objects-normal/arm64/ofxOscMessageOstreamExtension.o
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I just remove `ofxOscMessageOstreamExtension.h|cpp` files from the Xcode sidebar and everything is fine, but not sure why the error pops up now. (maybe I previously already removed the files and forgot about it)

**Comment by 2bbb** [comment]
hmmmm... it is wired.
I don't know why it doesn't happen on my envs...
but I added if macro with version what official `<<` operator on ofxOscMessage is introduced.

please check latest master.

**Comment by 2bbb** [comment]
@artificiel 
I checked on oF0.12.0 release and no errors.
I will close this issue.

please reopen if you still get error!
thanks!
